/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElLoading: typeof import('element-plus/es')['ElLoading']
  const ElLoadingService: typeof import('element-plus/es')['ElLoadingService']
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
}
