/* This file is generated by Ziggy. */
declare module 'zig     gy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "v1.auth.login": [],
    "v1.auth.registration": [],
    "v1.zomboid.index": [],
    "v1.zomboid.players.index": [],
    "v1.auth.index": [],
    "v1.zomboid.start": [],
    "v1.zomboid.down": [],
    "v1.zomboid.restart": [],
    "welcome": [],
    "login": [],
    "admin.dashboard": []
}
}
export {};
