version: "3"

services:
    nginx:
        container_name: "${APP_NAME:-pzadmin}_nginx"
        build: ./nginx
        ports:
            - "${APP_HTTP:-80}:80"
            - "${APP_HTTPS:-433}:433"
        networks:
            - backend
        links:
            - fpm
        volumes:
            - ./../:/var/www/html
            - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/config/sites-available/:/etc/nginx/sites-available/
            - ./nginx/config/sites-enabled/:/etc/nginx/sites-enabled/
            - ./nginx/config/nginxconfig.io/:/etc/nginx/nginxconfig.io/
            - ./nginx/logs/:/var/log/nginx/

    fpm:
        container_name: "${APP_NAME:-pzadmin}_fpm"
        build: ./fpm
        networks:
            - backend
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./../:/var/www/html
            - ./fpm/config/www.conf:/usr/local/etc/php-fom.d/www.conf
            - ./fpm/logs/fpm-php.www.log:/var/log/fpm-php.www.log:ro

    php:
        container_name: "${APP_NAME:-pzadmin}_php"
        build: ./php
        volumes:
            - ./../:/var/www/html

    php-setup:
        container_name: "${APP_NAME:-pzadmin}_php-setup"
        build: ./php
        depends_on:
            - php
        restart: "no"
        entrypoint: ["bash", "/root/scripts/setup.sh"]
        volumes:
            - ./../:/var/www/html

    php-vite-dev:
        container_name: "${APP_NAME:-pzadmin}_php-vite-dev"
        build: ./php
        ports:
            - "5173:5173"
        depends_on:
            - php-setup
        restart: "always"
        entrypoint: [ "bash", "/root/scripts/vite_dev.sh", "-d", "${APP_VITE_DEV}"]
        volumes:
            - ./../:/var/www/html

    zomboid:
        container_name: "${APP_NAME:-pzadmin}_zomboid"
        restart: unless-stopped
        build: ./zomboid
        env_file:
            - .env
        ports:
            - "${ZOMBOID_PORT_1}:16261/udp"
            - "${ZOMBOID_PORT_2}:16262/udp"
            - "${ZOMBOID_RCON_PORT}:27015"
        volumes:
            # Server data
            - ./zomboid/storage/data:/root/Zomboid
            # Workshop mods folder
            - ./zomboid/storage/workshop-mods:/pz-dedicated/steamapps/workshop

networks:
    backend:
        driver: bridge
