version: "3"

services:
    nginx:
        container_name: "${APP_NAME:-pzadmin}_nginx"
        build: ./nginx
        ports:
            - "${APP_HTTP:-80}:80"
            - "${APP_HTTPS:-433}:433"
            - "${VITE_REVERB_PORT:-8080}:8080"
            - "${VITE_PORT:-5173}:5173"
            - "${INERTIA_PORT:-13714}:13714"
        networks:
            - backend
        links:
            - fpm
            - php-laravel-reverb
            - php-vite-dev
        volumes:
            - "${STORAGE_APP}:/var/www/html"
            - "${STORAGE_NGINX}/logs/:/var/log/nginx/"
            - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/config/sites-available/:/etc/nginx/sites-available/
            - ./nginx/config/sites-enabled/:/etc/nginx/sites-enabled/
            - ./nginx/config/nginxconfig.io/:/etc/nginx/nginxconfig.io/

    fpm:
        container_name: "${APP_NAME:-pzadmin}_fpm"
        build: ./fpm
        networks:
            - backend
        volumes:
            - "${DOCKER_SOCKET}:/var/run/docker.sock:www-data"
            - "${STORAGE_APP}:/var/www/html"
#           - "${STORAGE_FPM}/logs/fpm-php.www.log:/var/log/fpm-php.www.log:ro"
            - ./fpm/config/www.conf:/usr/local/etc/php-fom.d/www.conf

    php:
        container_name: "${APP_NAME:-pzadmin}_php"
        build: ./php
        volumes:
            - "${STORAGE_APP}:/var/www/html"

    php-setup:
        container_name: "${APP_NAME:-pzadmin}_php-setup"
        build: ./php
        depends_on:
            - php
        restart: "no"
        entrypoint: ["bash", "/root/scripts/setup.sh"]
        volumes:
            - "${STORAGE_APP}:/var/www/html"

    php-vite-dev:
        container_name: "${APP_NAME:-pzadmin}_php-vite-dev"
        build: ./php
        networks:
            - backend
        depends_on:
            - php-setup
        restart: "always"
        entrypoint: [ "bash", "/root/scripts/vite_dev.sh", "-d", "${APP_VITE_DEV}"]
        volumes:
            - "${STORAGE_APP}:/var/www/html"

    php-laravel-reverb:
        container_name: "${APP_NAME:-pzadmin}_php-laravel-reverb"
        build: ./php
        networks:
            - backend
        depends_on:
            - php-setup
        restart: "always"
        entrypoint: [ "bash", "/root/scripts/laravel_reverb.sh" ]
        volumes:
            - "${STORAGE_APP}:/var/www/html"

    zomboid:
        container_name: "${APP_NAME:-pzadmin}_zomboid"
        restart: unless-stopped
        build: ./zomboid
        env_file:
            - ./../.env
        ports:
            - "${ZOMBOID_PORT_1}:16261/udp"
            - "${ZOMBOID_PORT_2}:16262/udp"
            - "${ZOMBOID_STEAM_PORT_1}:8766"
            - "${ZOMBOID_STEAM_PORT_2}:8767"
            - "${ZOMBOID_RCON_PORT}:27015"
        volumes:
            # Server data
            - "${STORAGE_ZOMBOID_DATA}:/root/Zomboid"
            # Workshop mods folder
            - "${STORAGE_ZOMBOID_MODS}:/pz-dedicated/steamapps/workshop"

networks:
    backend:
        driver: bridge
