version: "3"

services:
    nginx:
        container_name: "${APP_NAME:-pzadmin}_nginx"
        build: ./nginx
        ports:
            - "${APP_HTTP:-80}:80"
            - "${APP_HTTPS:-433}:433"
            - "${VITE_REVERB_PORT:-8080}:8080"
            - "${VITE_PORT:-5173}:5173"
            - "${INERTIA_PORT:-13714}:13714"
        networks:
            - backend
        links:
            - fpm
            - php-laravel-reverb
            - php-vite-dev
        volumes:
            - ./../:/var/www/html
            - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/config/sites-available/:/etc/nginx/sites-available/
            - ./nginx/config/sites-enabled/:/etc/nginx/sites-enabled/
            - ./nginx/config/nginxconfig.io/:/etc/nginx/nginxconfig.io/
            - ./nginx/logs/:/var/log/nginx/

    fpm:
        container_name: "${APP_NAME:-pzadmin}_fpm"
        build: ./fpm
        networks:
            - backend
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:www-data
            - ./../:/var/www/html
            - ./fpm/config/www.conf:/usr/local/etc/php-fom.d/www.conf
            - ./fpm/logs/fpm-php.www.log:/var/log/fpm-php.www.log:ro

    php:
        container_name: "${APP_NAME:-pzadmin}_php"
        build: ./php
        volumes:
            - ./../:/var/www/html

    php-setup:
        container_name: "${APP_NAME:-pzadmin}_php-setup"
        build: ./php
        depends_on:
            - php
        restart: "no"
        entrypoint: ["bash", "/root/scripts/setup.sh"]
        volumes:
            - ./../:/var/www/html

    php-vite-dev:
        container_name: "${APP_NAME:-pzadmin}_php-vite-dev"
        build: ./php
        networks:
            - backend
        depends_on:
            - php-setup
        restart: "always"
        entrypoint: [ "bash", "/root/scripts/vite_dev.sh", "-d", "${APP_VITE_DEV}"]
        volumes:
            - ./../:/var/www/html

    php-laravel-reverb:
        container_name: "${APP_NAME:-pzadmin}_php-laravel-reverb"
        build: ./php
        networks:
            - backend
        depends_on:
            - php-setup
        restart: "always"
        entrypoint: [ "bash", "/root/scripts/laravel_reverb.sh" ]
        volumes:
            - ./../:/var/www/html

    php-inertia:
        container_name: "${APP_NAME:-pzadmin}_php-inertia"
        build: ./php
        networks:
            - backend
        depends_on:
            - php-setup
        restart: "always"
        entrypoint: [ "bash", "/root/scripts/inertia.sh" ]
        volumes:
            - ./../:/var/www/html


    zomboid:
        container_name: "${APP_NAME:-pzadmin}_zomboid"
        restart: unless-stopped
        build: ./zomboid
        env_file:
            - .env
        ports:
            - "${ZOMBOID_PORT_1}:16261/udp"
            - "${ZOMBOID_PORT_2}:16262/udp"
            - "${ZOMBOID_RCON_PORT}:27015"
        volumes:
            # Server data
            - ./zomboid/storage/data:/root/Zomboid
            # Workshop mods folder
            - ./zomboid/storage/workshop-mods:/pz-dedicated/steamapps/workshop

networks:
    backend:
        driver: bridge
